# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  generate:
    desc: Build the web UI assets
    cmds:
      - go generate ./server/...

  server:
    desc: Generate the web UI and run the server
    deps: [generate]
    cmds:
      - go run . server

  agent:
    desc: Run the agent TUI
    cmds:
      - go run .

  install:
    desc: Install wingman using go install
    deps: [generate]
    cmds:
      - go build -o wingman . && mv wingman $(go env GOPATH)/bin/

  run:
    desc: Install and run wingman
    deps: [install]
    cmds:
      - $(go env GOPATH)/bin/wingman
