# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  ui:
    desc: Build the web UI
    dir: pkg/server/ui
    cmds:
      - npm install
      - npm run build

  install:
    desc: Install wingman using go install
    deps: [ui]
    cmds:
      - go build -o wingman . && mv wingman $(go env GOPATH)/bin/

  run:
    desc: Install and run wingman
    deps: [install]
    cmds:
      - $(go env GOPATH)/bin/wingman
