// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSettings():Promise<main.Settings>;

export function OpenWorkspace(arg1:string):Promise<void>;

export function SaveSettings(arg1:main.Settings):Promise<void>;

export function SelectFolder():Promise<string>;
